### ISSUE TITLE
ACPI aest driver probe failed in Linux kernel v5.15

### ISSUE THREAD

**Issue by bobolmw** [AmpereComputing/ampere-lts-kernel#148]
After apply patch in https://github.com/AmpereComputing/ampere-lts-kernel/issues/97, the aest driver init failed. In dmesg, show error logs:

```
[    0.029014] ACPI AEST: Failed to get AEST table
```

**Comment by adamliyi** [comment]
Close. We need to enable "Processor OS-first" in BIOS.
